branches:
    only:
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0

notifications:
  email: false

after_success:
  - julia -e 'import Pkg; Pkg.instantiate(); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: deploy docs
      os: linux
      julia: 1.0
      script:
        - julia -e 'import Pkg; Pkg.instantiate(); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
      after_success: skip
